# Generated by Django 2.0.1 on 2018-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20180110_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipespost',
            name='recipe_rating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
