# Generated by Django 2.0.1 on 2018-01-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipespost_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipespost',
            name='recipe_rating',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
