# Generated by Django 2.0.1 on 2018-01-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20180110_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipespost',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
